// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using CoreGraphics;
using Foundation;
using UIKit;

namespace CollectionViewPlayground.iOS
{
	public partial class TwoColumnViewCollectionViewCell : UICollectionViewCell
	{
		public UIView ViewContainer => OutletViewContainer;
		
		// public TwoColumnViewCollectionViewCell(IntPtr handle) : base(handle)
		// {
		// 	InitXib();
		// }
		[Export("initWithFrame:")]
		public TwoColumnViewCollectionViewCell(CGRect cgRect) : base(cgRect)
		{
			InitXib();
		}

		public TwoColumnViewCollectionViewCell(NSCoder coder) : base(coder)
		{
			InitXib();
		}
        
		private void InitXib()
		{
			var view = LoadNib();
			view.Frame = Bounds;
			AddSubview(view);
		}

		private UIView LoadNib()
		{
			var bundle = NSBundle.MainBundle;
			var nib = UINib.FromName("TwoCollumnViewCollectionViewCell", bundle);
			var view = nib.Instantiate(this, null).FirstOrDefault() as UIView;
			return view;
		}
	}
}
